### ISSUE TITLE
API responding with interstitial HTML instead of JSON

### ISSUE THREAD

**Issue by 0505gonzalez** [coinsph/api#6]
Repro steps:

Try to make a request to http://coins.ph/d/api/payout-outlets from web application.

Expected: Get back a JSON response.

Actual: Get back html response, which says "Checking your browser before accessing coins.ph." 

Is this a bug or is there some kind of workaround?

**Comment by avendael** [comment]
If you try https://coins.ph/api/internal/payout-outlets, do you get the same response?

**Comment by runarp** [comment]
Hi @0505gonzalez looks like CF was validating the browser.  I've updated PageRules to make sure it's white-listed.

**Comment by 0505gonzalez** [comment]
Great, that did the trick. Thanks @runarp for the super quick turnaround!
